import React from 'react';
export function Card({ title, eyebrow, actions, children, footer, padding = 24, inverse, elevated, interactive, onClick, style }) {
  const [hover, setHover] = React.useState(false);
  return React.createElement('section', { onClick, role: interactive ? 'button' : undefined, tabIndex: interactive ? 0 : undefined, onKeyDown: interactive ? (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onClick && onClick(); } } : undefined, onMouseEnter: () => setHover(true), onMouseLeave: () => setHover(false), style: { background: inverse ? 'var(--surface-inverse-raised)' : 'var(--surface-card)', color: inverse ? '#fff' : 'var(--text-primary)', border: '1px solid ' + (inverse ? 'var(--border-inverse)' : hover && interactive ? 'var(--border-strong)' : 'var(--border-default)'), borderRadius: 'var(--radius-lg)', boxShadow: elevated ? 'var(--shadow-md)' : hover && interactive ? 'var(--shadow-md)' : 'var(--shadow-sm)', display: 'flex', flexDirection: 'column', cursor: interactive ? 'pointer' : 'default', transition: 'box-shadow var(--duration-base) var(--ease-out), border-color var(--duration-base)', fontFamily: 'var(--font-body)', ...style } },
    (title || eyebrow || actions) ? React.createElement('header', { style: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16, padding: padding + 'px ' + padding + 'px 0' } },
      React.createElement('div', { style: { minWidth: 0, flex: '1 1 auto' } }, eyebrow ? React.createElement('div', { style: { fontFamily: 'var(--font-mono)', fontWeight: 500, fontSize: 11, letterSpacing: '.08em', textTransform: 'uppercase', color: inverse ? 'var(--text-on-inverse-muted)' : 'var(--text-muted)', marginBottom: 4 } }, eyebrow) : null,
        title ? React.createElement('h3', { style: { fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 22, lineHeight: 1.2, textTransform: 'uppercase', margin: 0, letterSpacing: '-.01em', overflowWrap: 'anywhere', textWrap: 'balance' } }, title) : null),
      actions ? React.createElement('div', { style: { display: 'flex', gap: 8, flex: 'none' } }, actions) : null) : null,
    React.createElement('div', { style: { padding, flex: 1 } }, children),
    footer ? React.createElement('footer', { style: { padding: '12px ' + padding + 'px', borderTop: '1px solid ' + (inverse ? 'var(--border-inverse)' : 'var(--border-default)'), display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 } }, footer) : null);
}
